project_id = "hmnyizoihyaqtxnlutvg"

[functions.seed-itbi-data]
verify_jwt = false

[functions.sync-itbi-daily]
verify_jwt = false

[functions.send-lead-notification]
verify_jwt = false

[functions.geo-itbi-clusters]
verify_jwt = false

[functions.search-logradouros-prefeitura]
verify_jwt = false

[functions.send-followup-email]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false
