// Lista de bairros oficiais da cidade do Rio de Janeiro (formato uppercase
// usado nas tabelas ITBI). Lista resumida com os bairros mais buscados.
export const BAIRROS_RIO: string[] = [
  "BARRA DA TIJUCA",
  "RECREIO DOS BANDEIRANTES",
  "JACAREPAGUA",
  "ITANHANGA",
  "JOA",
  "CAMORIM",
  "VARGEM GRANDE",
  "VARGEM PEQUENA",
  "FREGUESIA",
  "TAQUARA",
  "PECHINCHA",
  "ANIL",
  "CURICICA",
  "GARDENIA AZUL",
  "CIDADE DE DEUS",
  "IPANEMA",
  "LEBLON",
  "COPACABANA",
  "LEME",
  "BOTAFOGO",
  "FLAMENGO",
  "LARANJEIRAS",
  "CATETE",
  "GLORIA",
  "URCA",
  "HUMAITA",
  "COSME VELHO",
  "GAVEA",
  "JARDIM BOTANICO",
  "LAGOA",
  "SAO CONRADO",
  "VIDIGAL",
  "CENTRO",
  "TIJUCA",
  "VILA ISABEL",
  "GRAJAU",
  "MARACANA",
  "ANDARAI",
  "ALTO DA BOA VISTA",
  "USINA",
  "PRACA DA BANDEIRA",
  "MEIER",
  "CACHAMBI",
  "ENGENHO NOVO",
  "LINS DE VASCONCELOS",
  "RIACHUELO",
  "ROCHA",
  "SAO CRISTOVAO",
  "BENFICA",
  "MANGUEIRA",
  "VASCO DA GAMA",
  "ILHA DO GOVERNADOR",
  "JARDIM GUANABARA",
  "JARDIM CARIOCA",
  "PORTUGUESA",
  "MONERO",
  "COCOTA",
  "FREGUESIA (ILHA)",
  "BANGU",
  "CAMPO GRANDE",
  "SANTA CRUZ",
  "GUARATIBA",
  "PEDRA DE GUARATIBA",
  "SEPETIBA",
  "REALENGO",
  "PADRE MIGUEL",
  "SENADOR CAMARA",
  "MADUREIRA",
  "CASCADURA",
  "PIEDADE",
  "QUINTINO BOCAIUVA",
  "ENGENHO DE DENTRO",
  "OSVALDO CRUZ",
  "BENTO RIBEIRO",
  "MARECHAL HERMES",
  "DEL CASTILHO",
  "MARIA DA GRACA",
  "INHAUMA",
  "PENHA",
  "OLARIA",
  "RAMOS",
  "BONSUCESSO",
  "BRAS DE PINA",
  "CORDOVIL",
  "VIGARIO GERAL",
  "PARADA DE LUCAS",
  "JARDIM AMERICA",
  "IRAJA",
  "VICENTE DE CARVALHO",
  "ROCHA MIRANDA",
  "PAVUNA",
  "ANCHIETA",
  "GUADALUPE",
  "DEODORO",
  "VILA MILITAR",
  "MAGALHAES BASTOS",
  "JABOUR",
  "BARRA DE GUARATIBA",
  "SANTO CRISTO",
  "GAMBOA",
  "SAUDE",
  "CAJU",
];

// Bairros com cobertura forte de dados ITBI (base densa).
export const BAIRROS_COBERTURA_FORTE = new Set<string>([
  "BARRA DA TIJUCA",
  "RECREIO DOS BANDEIRANTES",
  "JACAREPAGUA",
  "ITANHANGA",
  "JOA",
  "CAMORIM",
]);

export function normalizeBairro(input: string): string {
  return (input || "")
    .toUpperCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .trim();
}

export function isBairroCoberturaForte(input: string): boolean {
  return BAIRROS_COBERTURA_FORTE.has(normalizeBairro(input));
}